#!/bin/sh

# Wait for internet to be up...
while true; do
if ping -q -c 1 -W 1 1.0.0.1 >/dev/null; then
break
else
sleep 1
fi
done

logger "Internet is up, routing vlan4..."

# Setup VLAN4 on the CPU as well so we can talk to it
robocfg vlan 4 ports "0t 5t"

# Add VLAN4 as a physical interface
vconfig add eth0 4

logger "Requesting IP-address and setting up static routes for vlan4"
# Request an IP-address and setup static routes
udhcpc -i vlan4 --clientid-none -O msstaticroutes -O staticroutes -V IPTV_RG -s /jffs/scripts/vlan4.script -p /var/run/vlan4.pid -b -O33 -O249

logger "Restart IGMP proxy"
# Restart IGMP proxy
sleep 20
/usr/bin/killall igmpproxy

logger "Waited 20 seconds and killed igmpproxy"

sleep 1
/usr/sbin/igmpproxy /jffs/configs/igmpproxy.conf
logger "Loaded custom igmpproxy.conf"